name: Build_x86_64_wjq

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 20 * * *
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex node-uglify gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint device-tree-compiler libuv-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: DIY packages
      working-directory: ./openwrt
      run: |
        cd package
        mkdir openwrt-packages
        cd openwrt-packages
        # git clone https://github.com/Ameykyl/luci-app-koolproxyr
        # git clone https://github.com/openwrt-develop/luci-theme-atmaterial
        # git clone https://github.com/Aslin-Ameng/luci-theme-light
        # git clone https://github.com/tty228/luci-app-serverchan
        # git clone https://github.com/happyzhang1995/openwrt-adguardhome
        # git clone https://github.com/happyzhang1995/luci-app-adguardhome
        # git clone https://github.com/rufengsuixing/luci-app-adguardhome
        # git clone https://github.com/kuoruan/openwrt-frp
        git clone https://github.com/destan19/OpenAppFilter
        git clone https://github.com/rosywrt/luci-theme-rosy
        git clone https://github.com/jerrykuku/luci-theme-argon
        git clone https://github.com/Leo-Jo-My/luci-theme-opentomcat
        git clone https://github.com/Leo-Jo-My/luci-theme-opentomato

    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a
        
    - name: Configuration Customization - Build_x86_64_wjq
      env:
        CONFIG_FILE: 'x86_64_wjq.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
        
#    - name: Assemble artifact
#      run: |
#          rm -rf ./artifact/
#          mkdir -p ./artifact/
#          find openwrt/bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
#          find openwrt/bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
#          find openwrt/bin/targets/ -name "*combined*vmdk*" | xargs -i mv -f {} ./artifact/
          
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_x86_64_wjq
        path: ./artifact/
