name: Build OpenWrt-Test

on: 
  release:
    types: [published]

  push:
    branches: 
      - master

  schedule:
    - cron: 0 4 * * 6
  
  watch:
    types: [started]

env:
  ftp_port: ${{ secrets.FTP_PORT }}
  ftp_username: ${{ secrets.FTP_USERNAME }}
  ftp_psw: ${{ secrets.FTP_PSW }}
  ftp_ip: ${{ secrets.FTP_IP }}
  TargetPath: openwrt
  upload_file_1: crontab_list.sh

jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Upload firmware to my NAS
      run: |
        curl -SLO https://raw.githubusercontent.com/LXK9301/jd_scripts/master/docker/crontab_list.sh
        echo $ftp_psw > /tmp/rsync.psw && chmod 600 /tmp/rsync.psw
        rsync -avzP --password-file=/tmp/rsync.psw -e $upload_file_1 $ftp_username@$ftp_ip::$TargetPath
        echo "All Released Files Uploaded to GXNAS"
    
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
